---
- hosts: localhost
  connection: local
   azure_subscription_id: "40a25577-60ff-462c-8ff2-a386981b8262"
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: meronmm
        location: northeurope
      register: rg
    - debug:
        var: rg
        
