---
- hosts: all
  connection: local
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: teast0110meron
        location: northeurope
      register: rg
    - debug:
        var: rg
