---
- name: Install Package
  hosts: localhost
  vars: 
    package: from_playbook
  tasks:
    - name: Create resource group
      azure_rm_resourcegroup:
        name: meronmm
        location: northeurope
      register: rg
    - debug:
        var: rg
        

        
