---
- name: Install Package
  hosts: localhost
  vars: 
    package: from_playbook

  tasks:
  - name: Ansible create file if it doesn't exist example
    file:
      path: "/home/meron/newfile"
      state: touch
